/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wildlife_tracker;

import javax.swing.JOptionPane;

/**
 *
 * @author oisinclarke
 */
public class MainGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGUI.class.getName());
    private SightingList sightingList;
    private ActionStack actionStack;
    private VerificationQueue verificationQueue;
    private int selectedIndex = -1;
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        System.out.println("Constructor started");
        initComponents();
        System.out.println("initComponents completed");
        sightingList = new SightingList();
        actionStack = new ActionStack();
        verificationQueue = new VerificationQueue();
        System.out.println("ADTs initialized");
    }
    
    
    private void displayAll(){
        displayArea.setText(sightingList.getAllSightings());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        observerField = new javax.swing.JTextField();
        locationField = new javax.swing.JTextField();
        speciesField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        displayAllButton = new javax.swing.JButton();
        verifyNextButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        undoButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        observerLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        speciesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        observerField.setActionCommand("observerField");

        locationField.setActionCommand("locationField");

        speciesField.setActionCommand("speciesField");

        addButton.setText("Add");
        addButton.setActionCommand("addButton");
        addButton.addActionListener(this::addButtonActionPerformed);

        displayAllButton.setText("Display");
        displayAllButton.setActionCommand("displayAllButton");
        displayAllButton.addActionListener(this::displayAllButtonActionPerformed);

        verifyNextButton.setText("Verify");
        verifyNextButton.setActionCommand("verifyNextButton");
        verifyNextButton.addActionListener(this::verifyNextButtonActionPerformed);

        deleteButton.setText("Delete");
        deleteButton.setActionCommand("deleteButton");
        deleteButton.addActionListener(this::deleteButtonActionPerformed);

        undoButton.setText("Undo");
        undoButton.setActionCommand("undoButton");
        undoButton.addActionListener(this::undoButtonActionPerformed);

        displayArea.setColumns(20);
        displayArea.setRows(5);
        jScrollPane1.setViewportView(displayArea);

        observerLabel.setText("Observer");

        locationLabel.setText("Location");

        speciesLabel.setText("Species");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(displayAllButton)
                            .addComponent(undoButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteButton)
                            .addComponent(verifyNextButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(addButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(speciesLabel)
                            .addComponent(observerLabel)
                            .addComponent(locationLabel))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(observerField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(locationField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(speciesField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(observerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(observerLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(locationLabel))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speciesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speciesLabel))
                .addGap(36, 36, 36)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(displayAllButton)
                            .addComponent(verifyNextButton))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteButton)
                            .addComponent(undoButton))
                        .addGap(72, 72, 72))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String species = speciesField.getText();
        String location = locationField.getText();
        String observer = observerField.getText();
        
        if (species.isEmpty() || location.isEmpty() || observer.isEmpty()){
            JOptionPane.showMessageDialog(this, "fill out all fields");
            return;
        }
        
        WildLifeSighting sighting = new WildLifeSighting(species, location, observer);
        sightingList.add(sighting);     
        verificationQueue.offer(sightingList.size() - 1);
        actionStack.push("Added: " + species);
        
        speciesField.setText("");
        locationField.setText("");
        observerField.setText("");
        displayAll();
    }//GEN-LAST:event_addButtonActionPerformed

    private void displayAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAllButtonActionPerformed
        // TODO add your handling code here:
        displayAll();
    }//GEN-LAST:event_displayAllButtonActionPerformed

    private void verifyNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyNextButtonActionPerformed
        // TODO add your handling code here:
        if (verificationQueue.isEmpty()){
            JOptionPane.showMessageDialog(this, "No sightings");
            return;
        }
        Integer index = verificationQueue.poll();
        WildLifeSighting sighting = sightingList.get(index);
        if(sighting != null){
            sighting.verify();
            actionStack.push("Verify");
            displayAll();
        }
    }//GEN-LAST:event_verifyNextButtonActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        // TODO add your handling code here:
        if (actionStack.isEmpty()){
            JOptionPane.showMessageDialog(this, "cant undo");
            return;
        }
    }//GEN-LAST:event_undoButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        if (selectedIndex == -1){
            JOptionPane.showMessageDialog(this, "select a sighting");
            return;
        }
        WildLifeSighting sighting = sightingList.get(selectedIndex);
        if (sighting != null){
            actionStack.push("Deleted: " + sighting.getSpecies());
            sightingList.remove(selectedIndex);
            selectedIndex = -1;
            displayAll();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton displayAllButton;
    private javax.swing.JTextArea displayArea;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField locationField;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JTextField observerField;
    private javax.swing.JLabel observerLabel;
    private javax.swing.JTextField speciesField;
    private javax.swing.JLabel speciesLabel;
    private javax.swing.JButton undoButton;
    private javax.swing.JButton verifyNextButton;
    // End of variables declaration//GEN-END:variables
}
